#version: '3'
#services:
#  web:
#    build: .
#    ports:
#     - "7474:7474"
#     - "7373:7373"
#     - "7687:7687"
#  redis:
#    image: "neo4j:latest"
neo4j:
  image: neo4j_web:latest
  ports:
    - "7474:7474"
    - "7687:7687"
  environment:
    NEO4J_AUTH: "none"